In [5]:
import pandas as pd

In [6]:
DB_PATH = "runs_index.csv"

DB = pd.read_csv(DB_PATH, index_col=0)
DB.head()

,collocation_time,computer,derivmatch_time,err-file,init,model,n_params,ncol,out-file,param,...,cfg.depth,cfg.dm_iters,cfg.hidden,cfg.lm_iters,cfg.signed_loss,cfg.linsolve,use_collocation,use_derivmatch,shapovalova,shooting
run_dir,,,,,,,,,,,,,,,,,,,,,
run_0BLmyHm6,0.000000,orcd,29.013032,/home/txenakis/projects/BVPsolver/logs/array_2...,default,mlp,243,0.0,/home/txenakis/projects/BVPsolver/logs/array_2...,none,...,2,10000,12,150,False,NaN,NaN,NaN,NaN,NaN
run_0CWrKVsW,0.000000,orcd,25.207717,/home/txenakis/projects/BVPsolver/logs/array_2...,default,GELU-scaled,188,0.0,/home/txenakis/projects/BVPsolver/logs/array_2...,none,...,2,10000,12,150,False,NaN,NaN,NaN,NaN,NaN
run_0Gfl62cO,30.977208,orcd,0.000000,/home/txenakis/projects/BVPsolver/logs/array_2...,default,GELU-scaled,188,0.0,/home/txenakis/projects/BVPsolver/logs/array_2...,none,...,2,10000,16,150,False,NaN,NaN,NaN,NaN,NaN
run_0H5EbMNc,16.495440,orcd,29.014588,/home/txenakis/projects/BVPsolver/logs/array_2...,default,stiff,318,0.0,/home/txenakis/projects/BVPsolver/logs/array_2...,none,...,2,10000,12,150,False,NaN,NaN,NaN,NaN,NaN
run_0ehx44A8,141.590429,orcd,29.398251,/home/txenakis/projects/BVPsolver/logs/array_2...,default,stiff,816,0.0,/home/txenakis/projects/BVPsolver/logs/array_2...,none,...,2,10000,16,150,False,qr,NaN,NaN,NaN,NaN

In [10]:
print(DB["model"].unique())
print(DB["problem"].unique())
print(DB["pretraining"].unique())
print(DB["training"].unique())

['mlp' 'GELU-scaled' 'stiff' nan]
['rober' 'orego' 'hires' 'vanderpol' 'pollu' 'davis-skodje']
['derivmatch' 'none' nan]
['none' 'collocation' 'shooting' 'shapovalova' nan]

In [21]:
nn = DB[(DB["problem"] == "vanderpol") & (DB["model"] == "stiff") & (DB["pretraining"] == "derivmatch") & (DB["training"] == "collocation")]
nn = DB[(DB["problem"] == "pollu") & (DB["model"] == "stiff") & (DB["pretraining"] == "derivmatch") & (DB["training"] == "collocation")]
nn

,collocation_time,computer,derivmatch_time,err-file,init,model,n_params,ncol,out-file,param,...,cfg.depth,cfg.dm_iters,cfg.hidden,cfg.lm_iters,cfg.signed_loss,cfg.linsolve,use_collocation,use_derivmatch,shapovalova,shooting
run_dir,,,,,,,,,,,,,,,,,,,,,
run_B8TA6bwb,9233.050914,orcd,51.485259,/home/txenakis/projects/BVPsolver/logs/array_2...,default,stiff,4744,0.0,/home/txenakis/projects/BVPsolver/logs/array_2...,none,...,3,30000,32,150,False,NaN,NaN,NaN,NaN,NaN
run_DpEiOWTX,9353.078582,orcd,50.724515,/home/txenakis/projects/BVPsolver/logs/array_2...,default,stiff,4744,0.0,/home/txenakis/projects/BVPsolver/logs/array_2...,none,...,3,30000,32,150,False,NaN,NaN,NaN,NaN,NaN
run_IDVpnloi,8742.292723,orcd,49.624766,/home/txenakis/projects/BVPsolver/logs/array_2...,default,stiff,4744,0.0,/home/txenakis/projects/BVPsolver/logs/array_2...,none,...,3,30000,32,150,False,NaN,NaN,NaN,NaN,NaN
run_fVbSaGWP,4577.776948,orcd,50.078244,/home/txenakis/projects/BVPsolver/logs/array_2...,default,stiff,4744,0.0,/home/txenakis/projects/BVPsolver/logs/array_2...,none,...,3,30000,32,150,False,NaN,NaN,NaN,NaN,NaN
run_xskaaKrJ,9233.955597,orcd,49.015577,/home/txenakis/projects/BVPsolver/logs/array_2...,default,stiff,4744,0.0,/home/txenakis/projects/BVPsolver/logs/array_2...,none,...,3,30000,32,150,False,NaN,NaN,NaN,NaN,NaN

In [9]:
DB.keys()

Index(['collocation_time', 'computer', 'derivmatch_time', 'err-file', 'init',
       'model', 'n_params', 'ncol', 'out-file', 'param', 'pretraining',
       'problem', 'profile', 'seed', 'shapovalova_time', 'shoot-iters',
       'shooting_time', 'sigma', 'timestamp', 'training', 'training_time',
       'cfg.amr_rounds', 'cfg.depth', 'cfg.dm_iters', 'cfg.hidden',
       'cfg.lm_iters', 'cfg.signed_loss', 'cfg.linsolve', 'use_collocation',
       'use_derivmatch', 'shapovalova', 'shooting'],
      dtype='object')

In [4]:
vdp1 = DB[(DB["problem"] == "vanderpol") & (DB["seed"] == 123)]
vdp1

,collocation_time,computer,derivmatch_time,err-file,init,model,n_params,ncol,out-file,param,...,cfg.depth,cfg.dm_iters,cfg.hidden,cfg.lm_iters,cfg.signed_loss,cfg.linsolve,use_collocation,use_derivmatch,shapovalova,shooting
run_dir,,,,,,,,,,,,,,,,,,,,,
run_9zWKNJ3v,0.0,NaN,13.560064,NaN,NaN,NaN,268,NaN,NaN,100.0,...,2,10000,12,150,True,NaN,False,True,NaN,NaN
run_FbGbX3v0,0.0,NaN,12.932799,NaN,NaN,NaN,268,NaN,NaN,100.0,...,2,10000,12,150,True,NaN,False,True,NaN,NaN
run_Uve46cZI,0.0,NaN,44.288030,NaN,default,stiff,268,0.0,NaN,100.0,...,2,10000,12,150,True,NaN,False,True,False,False